// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUID2SE9VkkW0usQy7a2dx_J3QLEO-Nx4',
    appId: '1:719036632964:web:a9bcbc45b1b03e6f5ed7d1',
    messagingSenderId: '719036632964',
    projectId: 'instagram-clone-2f993',
    authDomain: 'instagram-clone-2f993.firebaseapp.com',
    storageBucket: 'instagram-clone-2f993.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZB5SWpDbWL_uqLPWHj5F5vqJvmyx2oo',
    appId: '1:719036632964:android:b27e896876e7c4b85ed7d1',
    messagingSenderId: '719036632964',
    projectId: 'instagram-clone-2f993',
    storageBucket: 'instagram-clone-2f993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SmNu6wTaLbM2aNvqrI7Ivbu7dg8bVI0',
    appId: '1:719036632964:ios:7fbd9c9c442a51e35ed7d1',
    messagingSenderId: '719036632964',
    projectId: 'instagram-clone-2f993',
    storageBucket: 'instagram-clone-2f993.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-SmNu6wTaLbM2aNvqrI7Ivbu7dg8bVI0',
    appId: '1:719036632964:ios:7fbd9c9c442a51e35ed7d1',
    messagingSenderId: '719036632964',
    projectId: 'instagram-clone-2f993',
    storageBucket: 'instagram-clone-2f993.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUID2SE9VkkW0usQy7a2dx_J3QLEO-Nx4',
    appId: '1:719036632964:web:ff83d6423b56e3f75ed7d1',
    messagingSenderId: '719036632964',
    projectId: 'instagram-clone-2f993',
    authDomain: 'instagram-clone-2f993.firebaseapp.com',
    storageBucket: 'instagram-clone-2f993.firebasestorage.app',
  );
}
